- name: General omarchy post-install tasks
  hosts: localhost
  tasks:
    - name: Update omarchy if available
      ansible.builtin.shell: |
        if omarchy-update-available > /dev/null; then
          omarchy-update
          exit 254
        else
          exit 0
        fi
      register: result
      failed_when: result.rc != 0 and result.rc != 254
      changed_when: result.rc == 254
    - name: Install additional packages
      community.general.pacman:
        name:
          - tmux
          - firefox
          - 7zip
          - virtualbox
          - virtualbox-guest-iso
          - bitwarden
          - nextcloud-client
        state: present
      become: true
    - name: Create folder for git repos
      ansible.builtin.file:
        name: "~/repos"
        state: "directory"
    - name: Check and change current theme
      ansible.builtin.shell: |
        if [ $(omarchy-theme-current) = "Ethereal" ]; then
          exit 0
        else
          omarchy-theme-set "Ethereal"
          exit 254
        fi
      register: result
      failed_when: result.rc != 0 and result.rc != 254
      changed_when: result.rc == 254
    - name: Clone dotfiles-generic to repos folder
      ansible.builtin.git:
        repo: https://github.com/od00bi/dotfiles-generic.git
        dest: ~/repos/dotfiles-generic
- import_playbook: "../repos/dotfiles-generic/playbooks/tmux.yml"
